version: '3'
services:
  casino-nginx:
    build:
      context: ./casino/docker/development
      dockerfile: nginx.docker
    volumes:
      - ./casino:/app
    depends_on:
      - casino-php-fpm
    ports:
      - "8080:80"
  casino-php-fpm:
    build:
      context: ./casino/docker/development
      dockerfile: php-fpm.docker
    volumes:
      - ./casino:/app
  casino-php-cli:
    build:
      context: ./casino/docker/development
      dockerfile: php-cli.docker
    volumes:
      - ./casino:/app
      - composer:/root/.composer/cache
  casino-postgres:
    image: postgres:13.2
    volumes:
      - casino-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - "54321:5432"
  mailer:
    image: mailhog/mailhog
    ports:
      - "8081:8025"

volumes:
  casino-postgres:
  composer: