version: '3'
services:
  casino-nginx:
    image: ${REGISTRY_ADDRESS}/casino-nginx:${IMAGE_TAG}
    restart: always
    depends_on:
      - casino-php-fpm
    ports:
      - "80:80"
  casino-php-fpm:
    image: ${REGISTRY_ADDRESS}/casino-php-fpm:${IMAGE_TAG}
    restart: always
  casino-php-cli:
    image: ${REGISTRY_ADDRESS}/casino-php-cli:${IMAGE_TAG}